// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;

public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver("C:/Users/johna/selenium/test/chromedriver");
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void Test_defreight() {
    driver.Navigate().GoToUrl("http://freight-finder.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1265, 971);
    driver.FindElement(By.CssSelector(".nav-item:nth-child(2) > .nav-link")).Click();
    driver.FindElement(By.CssSelector(".nav-item:nth-child(3) > .nav-link")).Click();
    driver.FindElement(By.CssSelector(".nav-item:nth-child(4) > .nav-link")).Click();
   
  }
[Fact]
  public void Test_George() {
    driver.Navigate().GoToUrl("https://www.google.se/");
    driver.Manage().Window.Size = new System.Drawing.Size(1265, 971);
    driver.FindElement(By.Name("q")).SendKeys("george");
    driver.FindElement(By.Name("q")).SendKeys(Keys.Enter);
    
  }
   
}
